#!/usr/bin/bash

month=`date -d "1 day ago" '+%b'`
day=`date  -d "1 day ago" '+%-d'`
year=`date  -d "1 day ago" '+%Y'`

fulldate="${month,,}-${day}-${year}"
fullURL="https://www.mass.gov/doc/covid-19-raw-data-${fulldate}/download"

fullPath="./reports/${fulldate}"


echo $fullURL

wget -O ./reports/zipped ${fullURL}
unzip -d $fullPath ./reports/zipped
rm ./reports/zipped


